export const CONTRATORS_ALL_LABELS = {
  HEADER_TITLE: "Kontrahenci",
  HEADER_SUBTITLE: "Wszyscy",
  BOTTOM_ACCORDION_MENU_ADD_INVOICE: "Dodaj fakturę",
  BOTTOM_ACCORDION_MENU_EDIT: "Edytuj",
  BOTTOM_ACCORDION_MENU_INVOICES: "Faktury",
  BOTTOM_ACCORDION_MENU_DELETE: "Usuń",
};
