import { CONTRACTOR_LABELS, COMPANY_LABELS, INVOICE_SETTINGS_LABELS, PAYMENT_SETTINGS_LABELS, ITEM_LABELS } from "./GlobalObject.labels";

export const GLOBAL_OBJECT_CONTRACTOR: IInputProps[] = [
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_NAME,
    type: "text",
    name: "name",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_ADDRESS,
    type: "text",
    name: "address",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_ZIPCODE,
    type: "text",
    name: "zipcode",
    value: "",
    showName: true,
    validateList: ["ZIP_CODE_VALIDATE", "IS_EMPTY"],
    errorList: [],
    maxLength: 6,
  },
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_CITY,
    type: "text",
    name: "city",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_EMAIL,
    type: "text",
    name: "email",
    value: "",
    showName: true,
    validateList: ["EMAIL_VALIDATE"],
    errorList: [],
  },
  {
    label: CONTRACTOR_LABELS.CONTRACTOR_NIP,
    type: "text",
    name: "nip",
    value: "",
    showName: true,
    validateList: ["IS_NIP_EXIST", "IS_EMPTY", "NIP_VALIDATE"],
    errorList: [],
    maxLength: 13,
  },
];

export const GLOBAL_OBJECT_COMPANY: IInputProps[] = [
  {
    label: COMPANY_LABELS.COMPANY_NAME,
    type: "text",
    name: "name",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: COMPANY_LABELS.COMPANY_ADDRESS,
    type: "text",
    name: "address",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: COMPANY_LABELS.COMPANY_ZIPCODE,
    type: "text",
    name: "zipcode",
    value: "",
    showName: true,
    validateList: ["ZIP_CODE_VALIDATE", "IS_EMPTY"],
    errorList: [],
    maxLength: 6,
  },
  {
    label: COMPANY_LABELS.COMPANY_CITY,
    type: "text",
    name: "city",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: COMPANY_LABELS.COMPANY_EMAIL,
    type: "text",
    name: "email",
    value: "",
    showName: true,
    validateList: ["EMAIL_VALIDATE"],
    errorList: [],
  },
  {
    label: COMPANY_LABELS.COMPANY_NIP,
    type: "text",
    name: "nip",
    value: "",
    showName: true,
    validateList: ["IS_NIP_EXIST", "IS_EMPTY", "NIP_VALIDATE"],
    errorList: [],
    maxLength: 13,
  },
  {
    label: COMPANY_LABELS.COMPANY_PHONE_NUMBER,
    type: "text",
    name: "phoneNumber",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: COMPANY_LABELS.COMPANY_SITE_ADDRESS,
    type: "text",
    name: "siteAddress",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
];

export const GLOBAL_OBJECT_INVOICE_SETTINGS: IInputProps[] = [
  {
    label: INVOICE_SETTINGS_LABELS.INVOICE_SETTINGS_DATE_OF_ISSUE,
    type: "date",
    name: "dateOfIssue",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: INVOICE_SETTINGS_LABELS.INVOICE_SETTINGS_NUMBER,
    type: "text",
    name: "lastInvoiceNumber",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY", "IS_NUMERIC"],
    errorList: [],
  },
  {
    label: INVOICE_SETTINGS_LABELS.INVOICE_SETTINGS_YEAR,
    type: "text",
    name: "lastInvoiceYear",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY", "IS_NUMERIC"],
    errorList: [],
    minLength: 4,
    maxLength: 4,
  },
  {
    label: INVOICE_SETTINGS_LABELS.INVOICE_SETTINGS_PLACE_OF_ISSUE,
    type: "text",
    name: "placeOfIssue",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
];

export const GLOBAL_OBJECT_PAYMENT_SETTINGS: IInputProps[] = [
  {
    label: PAYMENT_SETTINGS_LABELS.PAYMENT_SETTINGS_DAYS_OF_PAYMENT,
    type: "number",
    name: "daysOfPayment",
    value: "14",
    showName: true,
    validateList: ["IS_EMPTY", "IS_NUMERIC"],
    errorList: [],
  },
  {
    label: PAYMENT_SETTINGS_LABELS.PAYEMNT_SETTINGS_ACCOUNT_NUMBER,
    type: "text",
    name: "accountNumber",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY", "ACCOUNT_NUMBER_VALIDATE"],
    errorList: [],
    maxLength: 32,
  },
  {
    label: PAYMENT_SETTINGS_LABELS.PAYMENT_SETTINGS_BANK_NAME,
    type: "text",
    name: "bankName",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
];

export const GLOBAL_OBJECT_ITEMS: IInputProps[] = [
  {
    label: ITEM_LABELS.ITEM_NAME,
    type: "text",
    name: "name",
    value: "",
    showName: true,
    validateList: ["IS_EMPTY"],
    errorList: [],
  },
  {
    label: ITEM_LABELS.ITEM_QUANTITY,
    type: "number",
    name: "quantity",
    value: "1",
    showName: true,
    step: 1,
    validateList: ["IS_EMPTY", "IS_NUMERIC"],
    errorList: [],
  },
  {
    label: ITEM_LABELS.ITEM_PRICE,
    type: "number",
    name: "price",
    value: "1",
    showName: true,
    validateList: ["IS_EMPTY", "IS_NUMERIC"],
    errorList: [],
  },
];
